name: ci

on:
  push:
    branches:
      - 'master'
  schedule:
    # run every month to rebuild on the latest pihole
    - cron: '0 0 1 * *'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/arm64
          # TODO we should push to different tags based on the pihole version
          tags: iloveitaly/pihole-scheduled-blocking:latest
      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          short-description: ${{ github.event.repository.description }}

      - uses: gautamkrishnar/keepalive-workflow@v1
